"""v3 phase 5a: consents

Revision ID: 067db81ef933
Revises: 5ef62e676536
Create Date: 2026-05-26 12:34:45.254690

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import minibank.db.models


# revision identifiers, used by Alembic.
revision: str = '067db81ef933'
down_revision: Union[str, Sequence[str], None] = '5ef62e676536'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('consents',
    sa.Column('id', minibank.db.models.GUID(), nullable=False),
    sa.Column('customer_user_id', minibank.db.models.GUID(), nullable=False),
    sa.Column('agent_user_id', minibank.db.models.GUID(), nullable=False),
    sa.Column('scope', sa.Enum('READ', 'READ_WRITE', name='consent_scope'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='consent_status'), nullable=False),
    sa.Column('granted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['agent_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['customer_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_consents_agent_user_id'), 'consents', ['agent_user_id'], unique=False)
    op.create_index(op.f('ix_consents_customer_user_id'), 'consents', ['customer_user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_consents_customer_user_id'), table_name='consents')
    op.drop_index(op.f('ix_consents_agent_user_id'), table_name='consents')
    op.drop_table('consents')
    # ### end Alembic commands ###
