"""v3 phase 3: sca_challenges + notifications

Revision ID: 0d08c76b856b
Revises: 68a6a8ad7f90
Create Date: 2026-05-26 12:15:24.238408

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import minibank.db.models


# revision identifiers, used by Alembic.
revision: str = '0d08c76b856b'
down_revision: Union[str, Sequence[str], None] = '68a6a8ad7f90'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('id', minibank.db.models.GUID(), nullable=False),
    sa.Column('user_id', minibank.db.models.GUID(), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('sca_challenges',
    sa.Column('id', minibank.db.models.GUID(), nullable=False),
    sa.Column('user_id', minibank.db.models.GUID(), nullable=False),
    sa.Column('code_hash', sa.String(length=255), nullable=False),
    sa.Column('linked_amount', sa.DECIMAL(precision=18, scale=2), nullable=False),
    sa.Column('linked_dest_iban', sa.String(length=40), nullable=False),
    sa.Column('pending_payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sca_challenges_user_id'), 'sca_challenges', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sca_challenges_user_id'), table_name='sca_challenges')
    op.drop_table('sca_challenges')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_table('notifications')
    # ### end Alembic commands ###
