"""v2: audit_log + jit_access_grants

Revision ID: 2e5ec2a8fd53
Revises: a321068c2f18
Create Date: 2026-05-26 10:54:49.292980

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import minibank.db.models


# revision identifiers, used by Alembic.
revision: str = '2e5ec2a8fd53'
down_revision: Union[str, Sequence[str], None] = 'a321068c2f18'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actor_user_id', minibank.db.models.GUID(), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('target_type', sa.String(length=32), nullable=True),
    sa.Column('target_id', sa.String(length=64), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_log_actor_user_id'), 'audit_log', ['actor_user_id'], unique=False)
    op.create_table('jit_access_grants',
    sa.Column('id', minibank.db.models.GUID(), nullable=False),
    sa.Column('agent_user_id', minibank.db.models.GUID(), nullable=False),
    sa.Column('customer_user_id', minibank.db.models.GUID(), nullable=False),
    sa.Column('ticket_id', sa.String(length=32), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('granted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['agent_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['customer_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jit_access_grants_agent_user_id'), 'jit_access_grants', ['agent_user_id'], unique=False)
    op.create_index(op.f('ix_jit_access_grants_customer_user_id'), 'jit_access_grants', ['customer_user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_jit_access_grants_customer_user_id'), table_name='jit_access_grants')
    op.drop_index(op.f('ix_jit_access_grants_agent_user_id'), table_name='jit_access_grants')
    op.drop_table('jit_access_grants')
    op.drop_index(op.f('ix_audit_log_actor_user_id'), table_name='audit_log')
    op.drop_table('audit_log')
    # ### end Alembic commands ###
