"""v3 phase 4: users.last_login_at + last_step_up_at

Revision ID: 5ef62e676536
Revises: 0d08c76b856b
Create Date: 2026-05-26 12:26:19.747380

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ef62e676536'
down_revision: Union[str, Sequence[str], None] = '0d08c76b856b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('last_step_up_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_step_up_at')
    op.drop_column('users', 'last_login_at')
    # ### end Alembic commands ###
