"""v3 phase 1: audit_log hash chain

Revision ID: 792744b29afd
Revises: 2e5ec2a8fd53
Create Date: 2026-05-26 12:04:10.334395

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '792744b29afd'
down_revision: Union[str, Sequence[str], None] = '2e5ec2a8fd53'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audit_log', sa.Column('prev_hash', sa.String(length=64), nullable=True))
    op.add_column('audit_log', sa.Column('row_hash', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('audit_log', 'row_hash')
    op.drop_column('audit_log', 'prev_hash')
    # ### end Alembic commands ###
