"""initial: users, accounts, transactions

Revision ID: a321068c2f18
Revises: 
Create Date: 2026-05-26 00:55:29.078968

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import minibank.db.models


# revision identifiers, used by Alembic.
revision: str = 'a321068c2f18'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', minibank.db.models.GUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('CUSTOMER', 'AGENT', 'ADMIN', 'SUPERVISOR', name='role'), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('pesel', sa.String(length=11), nullable=True),
    sa.Column('alt_id_type', sa.Enum('PASSPORT', 'RESIDENCE_CARD', 'UKR_STATUS', name='alt_id_type'), nullable=True),
    sa.Column('alt_id_value', sa.String(length=32), nullable=True),
    sa.Column('citizenship', sa.String(length=2), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('accounts',
    sa.Column('id', minibank.db.models.GUID(), nullable=False),
    sa.Column('owner_user_id', minibank.db.models.GUID(), nullable=False),
    sa.Column('holder_iban', sa.String(length=40), nullable=False),
    sa.Column('balance', sa.DECIMAL(precision=18, scale=2), nullable=False),
    sa.Column('currency', sa.Enum('PLN', 'EUR', 'USD', name='currency'), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('overdraft_limit', sa.DECIMAL(precision=18, scale=2), nullable=False),
    sa.Column('opened_on', minibank.db.models.IsoDate(), nullable=False),
    sa.Column('closed_on', minibank.db.models.IsoDate(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_accounts_owner_user_id'), 'accounts', ['owner_user_id'], unique=False)
    op.create_table('transactions',
    sa.Column('id', minibank.db.models.GUID(), nullable=False),
    sa.Column('source_account_id', minibank.db.models.GUID(), nullable=False),
    sa.Column('dest_account_id', minibank.db.models.GUID(), nullable=True),
    sa.Column('dest_iban', sa.String(length=40), nullable=True),
    sa.Column('amount', sa.DECIMAL(precision=18, scale=2), nullable=False),
    sa.Column('currency', sa.Enum('PLN', 'EUR', 'USD', name='currency'), nullable=False),
    sa.Column('title', sa.String(length=140), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('initiated_by_user_id', minibank.db.models.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['dest_account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['initiated_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['source_account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transactions_source_account_id'), 'transactions', ['source_account_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactions_source_account_id'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_accounts_owner_user_id'), table_name='accounts')
    op.drop_table('accounts')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
